// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8mHHgpV-iToROi1oPG4wSf1hIqkcjKkE',
    appId: '1:1037494444225:web:d5dffa9496ba1100c8f440',
    messagingSenderId: '1037494444225',
    projectId: 'csera-9cb70',
    authDomain: 'csera-9cb70.firebaseapp.com',
    storageBucket: 'csera-9cb70.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVbwM4UpIewuQMgx28vGjDjceEsTS9zb4',
    appId: '1:1037494444225:android:00471e58286b1ef6c8f440',
    messagingSenderId: '1037494444225',
    projectId: 'csera-9cb70',
    storageBucket: 'csera-9cb70.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBn-TI4As8lepUSc24U-O6CrH-lOUFJRBw',
    appId: '1:1037494444225:ios:8e6cac5febfca5c1c8f440',
    messagingSenderId: '1037494444225',
    projectId: 'csera-9cb70',
    storageBucket: 'csera-9cb70.appspot.com',
    iosBundleId: 'com.example.cseraApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBn-TI4As8lepUSc24U-O6CrH-lOUFJRBw',
    appId: '1:1037494444225:ios:cf6c4629101ad9f5c8f440',
    messagingSenderId: '1037494444225',
    projectId: 'csera-9cb70',
    storageBucket: 'csera-9cb70.appspot.com',
    iosBundleId: 'com.example.cseraApp.RunnerTests',
  );
}
